### PR TITLE
Use argparse in the commands.

### PR DESCRIPTION
**Pull request by Rafiot**
Only open for now.

Step 1 on #93

### CODE REVIEW

**Comment by Rafiot** [comment]
up?

**Comment by SnakeByteIL** [comment]
t seems to be working. First it didn't load for me because pycrypto was missing (from Crypto.Cipher import blowfish), after I installed that seems to be working well.

I took off the try test when loading modules from:
https://github.com/botherder/viper/blob/master/viper/core/plugins.py

I'm not 100% sure if this is why the rat module was not loading but it might be because of the try test this commit add in https://github.com/botherder/viper/blob/master/viper/common/abstracts.py"
try:
                self.parsed_args = self.parser.parse_args(self.args)
            except ArgumentErrorCallback as e:
                self.log(*e.get())


Maybe it will be wise to add some kind of "test" and let users know if they are missing a library?

**Comment by botherder** [comment]
Yes, that is true.

**Comment by SnakeByteIL** [comment]
Trying to reproduce the problem

**Comment by botherder** [comment]
I managed to figure out my issue and fix it. Yara had troubles and the rat module isn't notifying it. I'm on it, thanks.

**Pull request merged**
