### PR TITLE
Web update

### PR DESCRIPTION
**Pull request by kevthehermit**
There are 3 parts to this update. 

1.  New file browse input that correctly displays selected files. 

2.  Breadcrumbs added to file view so you can see the project / session you are in. 

breadcrumbs

3.  There is a new page linked from the nav bar. CLI. 
This page will allow you to run commands as if you were at the console. You can chain commands as per the CLI. This functionality is also extended to the modules page and if the command doesn't open a session, it will use the hash of the open page. Any commands in the CLI box will override the dropdown selections.

as an example 
```
find name *; open -l 2; strings -a
```

will results in 

cmd_output

You can switch between projects via a cli command. projects -s <project name>

as an example

```
projects -s dark_comet; find name *; open -l 1; rat -a 
```

In order to get output from commands as well as modules the commands had to be moved to the new ```self.log``` output style. The CLI still functions as expected.

### CODE REVIEW

**Comment by SnakeByteIL** [comment]
@kevthehermit I'm getting the following error when trying to download from VT:
module_results = module_cmdline(cmd_line)
TypeError: module_cmdline() takes exactly 2 arguments (1 given)

**Comment by SnakeByteIL** [comment]
hmmm fixed with adding empty string: 
module_results = module_cmdline(cmd_line,'') 
might wanna check it more deeply.

**Comment by kevthehermit** [comment]
Fixing Now, Passing a hash in is an option for other modules so it will open a session, i was not passing this in as False. Update incoming soon

**Comment by SnakeByteIL** [comment]
thanks

**Pull request merged**
