### PR TITLE
Json responses

### PR DESCRIPTION
**Pull request by lksnyder0**
Removed all HTTPError calls and replaced them with json responses.

### CODE REVIEW

**Comment by botherder** [comment]
Is there any particular reason to change this?

**Comment by lksnyder0** [comment]
I did this to standardize the output from the API. The HTTPerror function returns HTML. So if a call succeeded json was returned. If a call failed HTML was returned. This makes parsing the exact error much harder. I have preserved the behavior of HTTPerror while still returning json by returning the appropriate http code for each error.

**Comment by Chiggins** [comment]
I wanna :+1: @lksnyder0 on this one. Good idea to standardize so you only expect one format instead of many.

Also, as an aside, you can bunch multiple files into one commit, and not have a commit per file. :)

**Comment by lksnyder0** [comment]
Thanks for the thumbs up Chris.


Also, I like to make my commits as modular as possible. I will admit that is may have been an extreme case.










From: Chris Higgins
Sent: ‎Tuesday‎, ‎March‎ ‎10‎, ‎2015 ‎12‎:‎10‎ ‎PM
To: botherder/viper
Cc: Luke Snyder





I wanna  :+1: @lksnyder0 on this one. Good idea to standardize so you only expect one format instead of many.

Also, as an aside, you can bunch multiple files into one commit, and not have a commit per file. :)

**Comment by botherder** [comment]
Can you verify merge conflicts?

**Pull request closed without merging**
