### PR TITLE
Implement authenticode verification

### PR DESCRIPTION
**Pull request by jahrome**
Update to fit new codebase.

### CODE REVIEW

**Comment by jahrome** [comment]
Hi, is there something I can do to help so that the code be merged ?

**Comment by botherder** [comment]
I just need to go through my TODO list. As we're trying to fix the issue with argparse, the pull request has become impossible to merge. If you have the time, it would be great if you could update it with latest changes.

**Comment by jahrome** [comment]
Updated to fit argparse mecanism https://github.com/botherder/viper/pull/196

**Comment by botherder** [comment]
There's still some merge conflicts, if you can take a look at them please do. Otherwise I'll do it when I get more time.

**Comment by jahrome** [comment]
On 01/14/2015 04:33 PM, Nex wrote:
>
> There's still some merge conflicts, if you can take a look at them
> please do. Otherwise I'll do it when I get more time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/botherder/viper/pull/186#issuecomment-69933694>.
>
Have you tried with this PR: https://github.com/botherder/viper/pull/196 ?

**Pull request closed without merging**
