### PR TITLE
added new command: 'new' - create a new file

### PR DESCRIPTION
**Pull request by rommelfs**
Implementation of command 'new' which creates a new file in the current session.
This is basically useful for pasting email headers and similar things you want to keep track in 
a viper database.

### CODE REVIEW

**Comment by kevthehermit** [comment]
There are 'Notes' for that kind of thing.

**Comment by rommelfs** [comment]
I don't understand your comment, maybe there is a misunderstanding on my side.
My understanding based on the following example:
If I copy the source of a mail into the clipboard with the goal to analyze it with viper, I have to paste the source into a new file and open it with viper, in order to apply the 'email' module. Repeating for each mail.

It is nicer if I just create a new file from within viper, apply the 'email' module and decide to save it or not in a database.

Same applies for 'html' module and other text based actions.

I don't see how the notes module can help here.

**Comment by botherder** [comment]
I get what @rommelfs and I think it makes sense.

**Comment by botherder** [comment]
Thank you for your contribution.

**Pull request merged**
