### PR TITLE
Web update

### PR DESCRIPTION
**Pull request by kevthehermit**
Update to the web interface.

Adds a hex viewer tab to the file view. 

Changes the modules to use a drop down selection to run commands

Adds a spinner to show when module data is loading. (Spin.js)

### CODE REVIEW

**Comment by botherder** [comment]
I've been away. I need to catch up with pull requests. I'll do that in the next days.

**Comment by botherder** [comment]
@kevthehermit did you remove the text form to issue commands to execute modules? I think it would be useful to maintain both the menu and the text form, for people who are proficient with the command line syntax.

**Comment by kevthehermit** [comment]
Yeah that makes sense. Ill add the text form back in and update this pull

**Comment by botherder** [comment]
I'll merge in the meantime. Make a pull request as needed.

**Comment by SnakeByteIL** [comment]
Maybe something like an option to chose between "production" / "development" or "public" / "private". 
Since its a good Idea for public environment to have all the modules pre-made other than user input. 

if [public] in config:
 disable the text module

Else:
 show it in web.py? 

Just a thought...

**Comment by SnakeByteIL** [comment]
also was the virustotal module taken out on purpose ?

**Comment by botherder** [comment]
What do you mean it was taken out?

**Comment by SnakeByteIL** [comment]
Sorry needed to scroll down, my bad. (Sunday)

**Pull request merged**
